interface Country {
    isoCode: string;  
    numericCode: number;  
    name: string;  
    continent: string;  
    isEU: boolean;  
    isUN: boolean;  
  }
  
  // Данные стран
  const countries: { [key: string]: Country } = {
    ISOCodeAF: { isoCode: "AF", numericCode: 4, name: "Afghanistan", continent: "Asia", isEU: false, isUN: false },
    ISOCodeAX: { isoCode: "AX", numericCode: 248, name: "Åland Islands", continent: "Europe", isEU: false, isUN: true },
    ISOCodeAL: { isoCode: "AL", numericCode: 8, name: "Albania", continent: "Europe", isEU: false, isUN: true },
    ISOCodeDZ: { isoCode: "DZ", numericCode: 12, name: "Algeria", continent: "Africa", isEU: false, isUN: true },
    ISOCodeAS: { isoCode: "AS", numericCode: 16, name: "American Samoa", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeAD: { isoCode: "AD", numericCode: 20, name: "Andorra", continent: "Europe", isEU: false, isUN: true },
    ISOCodeAO: { isoCode: "AO", numericCode: 24, name: "Angola", continent: "Africa", isEU: false, isUN: true },
    ISOCodeAI: { isoCode: "AI", numericCode: 660, name: "Anguilla", continent: "Americas", isEU: false, isUN: true },
    ISOCodeAQ: { isoCode: "AQ", numericCode: 10, name: "Antarctica", continent: "", isEU: false, isUN: true },
    ISOCodeAG: { isoCode: "AG", numericCode: 28, name: "Antigua and Barbuda", continent: "Americas", isEU: false, isUN: true },
    ISOCodeAR: { isoCode: "AR", numericCode: 32, name: "Argentina", continent: "Americas", isEU: false, isUN: true },
    ISOCodeAM: { isoCode: "AM", numericCode: 51, name: "Armenia", continent: "Asia", isEU: false, isUN: true },
    ISOCodeAW: { isoCode: "AW", numericCode: 533, name: "Aruba", continent: "Americas", isEU: false, isUN: true },
    ISOCodeAU: { isoCode: "AU", numericCode: 36, name: "Australia", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeAZ: { isoCode: "AZ", numericCode: 31, name: "Azerbaijan", continent: "Asia", isEU: false, isUN: true },
    ISOCodeBS: { isoCode: "BS", numericCode: 44, name: "Bahamas", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBH: { isoCode: "BH", numericCode: 48, name: "Bahrain", continent: "Asia", isEU: false, isUN: true },
    ISOCodeBD: { isoCode: "BD", numericCode: 50, name: "Bangladesh", continent: "Asia", isEU: false, isUN: true },
    ISOCodeBB: { isoCode: "BB", numericCode: 52, name: "Barbados", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBY: { isoCode: "BY", numericCode: 112, name: "Belarus", continent: "Europe", isEU: false, isUN: false },
    ISOCodeBZ: { isoCode: "BZ", numericCode: 84, name: "Belize", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBJ: { isoCode: "BJ", numericCode: 204, name: "Benin", continent: "Africa", isEU: false, isUN: true },
    ISOCodeBM: { isoCode: "BM", numericCode: 60, name: "Bermuda", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBT: { isoCode: "BT", numericCode: 64, name: "Bhutan", continent: "Asia", isEU: false, isUN: true },
    ISOCodeBO: { isoCode: "BO", numericCode: 68, name: "Bolivia (Plurinational State of)", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBQ: { isoCode: "BQ", numericCode: 535, name: "Bonaire, Sint Eustatius and Saba", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBA: { isoCode: "BA", numericCode: 70, name: "Bosnia and Herzegovina", continent: "Europe", isEU: false, isUN: true },
    ISOCodeBW: { isoCode: "BW", numericCode: 72, name: "Botswana", continent: "Africa", isEU: false, isUN: true },
  
    ISOCodeBV: { isoCode: "BV", numericCode: 74, name: "Bouvet Island", continent: "Americas", isEU: false, isUN: true },
    ISOCodeBR: { isoCode: "BR", numericCode: 76, name: "Brazil", continent: "Americas", isEU: false, isUN: true },
    ISOCodeIO: { isoCode: "IO", numericCode: 86, name: "British Indian Ocean Territory", continent: "Africa", isEU: false, isUN: true },
    ISOCodeBN: { isoCode: "BN", numericCode: 96, name: "Brunei Darussalam", continent: "Asia", isEU: false, isUN: true },
    ISOCodeBF: { isoCode: "BF", numericCode: 854, name: "Burkina Faso", continent: "Africa", isEU: false, isUN: true },
    ISOCodeBI: { isoCode: "BI", numericCode: 108, name: "Burundi", continent: "Africa", isEU: false, isUN: false },
    ISOCodeCV: { isoCode: "CV", numericCode: 132, name: "Cabo Verde", continent: "Africa", isEU: false, isUN: true },
    ISOCodeKH: { isoCode: "KH", numericCode: 116, name: "Cambodia", continent: "Asia", isEU: false, isUN: true },
    ISOCodeCM: { isoCode: "CM", numericCode: 120, name: "Cameroon", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCA: { isoCode: "CA", numericCode: 124, name: "Canada", continent: "Americas", isEU: false, isUN: true },
    ISOCodeKY: { isoCode: "KY", numericCode: 136, name: "Cayman Islands", continent: "Americas", isEU: false, isUN: true },
    ISOCodeCF: { isoCode: "CF", numericCode: 140, name: "Central African Republic", continent: "Africa", isEU: false, isUN: true },
    ISOCodeTD: { isoCode: "TD", numericCode: 148, name: "Chad", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCL: { isoCode: "CL", numericCode: 152, name: "Chile", continent: "Americas", isEU: false, isUN: true },
    ISOCodeCN: { isoCode: "CN", numericCode: 156, name: "China", continent: "Asia", isEU: false, isUN: true },
    ISOCodeCX: { isoCode: "CX", numericCode: 162, name: "Christmas Island", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeCC: { isoCode: "CC", numericCode: 166, name: "Cocos (Keeling) Islands", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeCO: { isoCode: "CO", numericCode: 170, name: "Colombia", continent: "Americas", isEU: false, isUN: true },
    ISOCodeKM: { isoCode: "KM", numericCode: 174, name: "Comoros", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCG: { isoCode: "CG", numericCode: 178, name: "Congo", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCD: { isoCode: "CD", numericCode: 180, name: "Congo, Democratic Republic of the", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCK: { isoCode: "CK", numericCode: 184, name: "Cook Islands", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeCR: { isoCode: "CR", numericCode: 188, name: "Costa Rica", continent: "Americas", isEU: false, isUN: true },
    ISOCodeCI: { isoCode: "CI", numericCode: 384, name: "Côte d'Ivoire", continent: "Africa", isEU: false, isUN: true },
    ISOCodeCU: { isoCode: "CU", numericCode: 192, name: "Cuba", continent: "Americas", isEU: false, isUN: false },
    ISOCodeCW: { isoCode: "CW", numericCode: 531, name: "Curaçao", continent: "Americas", isEU: false, isUN: true },
    ISOCodeDJ: { isoCode: "DJ", numericCode: 262, name: "Djibouti", continent: "Africa", isEU: false, isUN: true },
    ISOCodeDM: { isoCode: "DM", numericCode: 212, name: "Dominica", continent: "Americas", isEU: false, isUN: true },
    ISOCodeDO: { isoCode: "DO", numericCode: 214, name: "Dominican Republic", continent: "Americas", isEU: false, isUN: true },
    ISOCodeEC: { isoCode: "EC", numericCode: 218, name: "Ecuador", continent: "Americas", isEU: false, isUN: true },
    ISOCodeEG: { isoCode: "EG", numericCode: 818, name: "Egypt", continent: "Africa", isEU: false, isUN: true },
    ISOCodeSV: { isoCode: "SV", numericCode: 222, name: "El Salvador", continent: "Americas", isEU: false, isUN: true },

    ISOCodeGQ: { isoCode: "GQ", numericCode: 226, name: "Equatorial Guinea", continent: "Africa", isEU: false, isUN: true },
    ISOCodeER: { isoCode: "ER", numericCode: 232, name: "Eritrea", continent: "Africa", isEU: false, isUN: true },
    ISOCodeSZ: { isoCode: "SZ", numericCode: 748, name: "Eswatini", continent: "Africa", isEU: false, isUN: true },
    ISOCodeET: { isoCode: "ET", numericCode: 231, name: "Ethiopia", continent: "Africa", isEU: false, isUN: true },
    ISOCodeFK: { isoCode: "FK", numericCode: 238, name: "Falkland Islands (Malvinas)", continent: "Americas", isEU: false, isUN: true },
    ISOCodeFO: { isoCode: "FO", numericCode: 234, name: "Faroe Islands", continent: "Europe", isEU: false, isUN: true },
    ISOCodeFJ: { isoCode: "FJ", numericCode: 242, name: "Fiji", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeGF: { isoCode: "GF", numericCode: 254, name: "French Guiana", continent: "Americas", isEU: false, isUN: true },
    ISOCodePF: { isoCode: "PF", numericCode: 258, name: "French Polynesia", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeTF: { isoCode: "TF", numericCode: 260, name: "French Southern Territories", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGA: { isoCode: "GA", numericCode: 266, name: "Gabon", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGM: { isoCode: "GM", numericCode: 270, name: "Gambia", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGE: { isoCode: "GE", numericCode: 268, name: "Georgia", continent: "Asia", isEU: false, isUN: true },
    ISOCodeGH: { isoCode: "GH", numericCode: 288, name: "Ghana", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGI: { isoCode: "GI", numericCode: 292, name: "Gibraltar", continent: "Europe", isEU: false, isUN: true },
    ISOCodeGL: { isoCode: "GL", numericCode: 304, name: "Greenland", continent: "Americas", isEU: false, isUN: true },
    ISOCodeGD: { isoCode: "GD", numericCode: 308, name: "Grenada", continent: "Americas", isEU: false, isUN: true },
    ISOCodeGP: { isoCode: "GP", numericCode: 312, name: "Guadeloupe", continent: "Americas", isEU: false, isUN: true },
    ISOCodeGU: { isoCode: "GU", numericCode: 316, name: "Guam", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeGT: { isoCode: "GT", numericCode: 320, name: "Guatemala", continent: "Americas", isEU: false, isUN: true },
    ISOCodeGG: { isoCode: "GG", numericCode: 831, name: "Guernsey", continent: "Europe", isEU: false, isUN: true },
    ISOCodeGN: { isoCode: "GN", numericCode: 324, name: "Guinea", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGW: { isoCode: "GW", numericCode: 624, name: "Guinea-Bissau", continent: "Africa", isEU: false, isUN: true },
    ISOCodeGY: { isoCode: "GY", numericCode: 328, name: "Guyana", continent: "Americas", isEU: false, isUN: true },
    ISOCodeHT: { isoCode: "HT", numericCode: 332, name: "Haiti", continent: "Americas", isEU: false, isUN: true },
    ISOCodeHM: { isoCode: "HM", numericCode: 334, name: "Heard Island and McDonald Islands", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeVA: { isoCode: "VA", numericCode: 336, name: "Holy See", continent: "Europe", isEU: false, isUN: true },
    ISOCodeHN: { isoCode: "HN", numericCode: 340, name: "Honduras", continent: "Americas", isEU: false, isUN: true },
    ISOCodeHK: { isoCode: "HK", numericCode: 344, name: "Hong Kong", continent: "Asia", isEU: false, isUN: true },
    ISOCodeIS: { isoCode: "IS", numericCode: 352, name: "Iceland", continent: "Europe", isEU: false, isUN: true },
    ISOCodeIN: { isoCode: "IN", numericCode: 356, name: "India", continent: "Asia", isEU: false, isUN: true },
    ISOCodeID: { isoCode: "ID", numericCode: 360, name: "Indonesia", continent: "Asia", isEU: false, isUN: true },
    ISOCodeIR: { isoCode: "IR", numericCode: 364, name: "Iran (Islamic Republic of)", continent: "Asia", isEU: false, isUN: false },
    ISOCodeIQ: { isoCode: "IQ", numericCode: 368, name: "Iraq", continent: "Asia", isEU: false, isUN: true },
    ISOCodeIM: { isoCode: "IM", numericCode: 833, name: "Isle of Man", continent: "Europe", isEU: false, isUN: true },
    ISOCodeIL: { isoCode: "IL", numericCode: 376, name: "Israel", continent: "Asia", isEU: false, isUN: true },
    ISOCodeJM: { isoCode: "JM", numericCode: 388, name: "Jamaica", continent: "Americas", isEU: false, isUN: true },
    ISOCodeJP: { isoCode: "JP", numericCode: 392, name: "Japan", continent: "Asia", isEU: false, isUN: true },
    ISOCodeJE: { isoCode: "JE", numericCode: 832, name: "Jersey", continent: "Europe", isEU: false, isUN: true },
    ISOCodeJO: { isoCode: "JO", numericCode: 400, name: "Jordan", continent: "Asia", isEU: false, isUN: true },
    ISOCodeKZ: { isoCode: "KZ", numericCode: 398, name: "Kazakhstan", continent: "Asia", isEU: false, isUN: true },
    ISOCodeKE: { isoCode: "KE", numericCode: 404, name: "Kenya", continent: "Africa", isEU: false, isUN: true },
    ISOCodeKI: { isoCode: "KI", numericCode: 296, name: "Kiribati", continent: "Oceania", isEU: false, isUN: true },
    ISOCodeKP: { isoCode: "KP", numericCode: 408, name: "Korea (Democratic People's Republic of)", continent: "Asia", isEU: false, isUN: false },
    ISOCodeKR: { isoCode: "KR", numericCode: 410, name: "Korea, Republic of", continent: "Asia", isEU: false, isUN: true },
    
  ISOCodeTV: { isoCode: "TV", numericCode: 798, name: "Tuvalu", continent: "Oceania", isEU: false, isUN: true },
  ISOCodeUG: { isoCode: "UG", numericCode: 800, name: "Uganda", continent: "Africa", isEU: false, isUN: true },
  ISOCodeUA: { isoCode: "UA", numericCode: 804, name: "Ukraine", continent: "Europe", isEU: false, isUN: true },
  ISOCodeAE: { isoCode: "AE", numericCode: 784, name: "United Arab Emirates", continent: "Asia", isEU: false, isUN: true },
  ISOCodeGB: { isoCode: "GB", numericCode: 826, name: "United Kingdom of Great Britain and Northern Ireland", continent: "Europe", isEU: false, isUN: true },
  ISOCodeUS: { isoCode: "US", numericCode: 840, name: "United States of America", continent: "Americas", isEU: false, isUN: true },
  ISOCodeUM: { isoCode: "UM", numericCode: 581, name: "United States Minor Outlying Islands", continent: "Oceania", isEU: false, isUN: true },
  ISOCodeUY: { isoCode: "UY", numericCode: 858, name: "Uruguay", continent: "Americas", isEU: false, isUN: true },
  ISOCodeUZ: { isoCode: "UZ", numericCode: 860, name: "Uzbekistan", continent: "Asia", isEU: false, isUN: true },
  ISOCodeVU: { isoCode: "VU", numericCode: 548, name: "Vanuatu", continent: "Oceania", isEU: false, isUN: true },
  ISOCodeVE: { isoCode: "VE", numericCode: 862, name: "Venezuela (Bolivarian Republic of)", continent: "Americas", isEU: false, isUN: false },
  ISOCodeVN: { isoCode: "VN", numericCode: 704, name: "Viet Nam", continent: "Asia", isEU: false, isUN: true },
  ISOCodeVG: { isoCode: "VG", numericCode: 92, name: "Virgin Islands (British)", continent: "Americas", isEU: false, isUN: true },
  ISOCodeVI: { isoCode: "VI", numericCode: 850, name: "Virgin Islands (U.S.)", continent: "Americas", isEU: false, isUN: true },
  ISOCodeWF: { isoCode: "WF", numericCode: 876, name: "Wallis and Futuna", continent: "Oceania", isEU: false, isUN: true },
  ISOCodeEH: { isoCode: "EH", numericCode: 732, name: "Western Sahara", continent: "Africa", isEU: false, isUN: true },
  ISOCodeYE: { isoCode: "YE", numericCode: 887, name: "Yemen", continent: "Asia", isEU: false, isUN: false },
  ISOCodeZM: { isoCode: "ZM", numericCode: 894, name: "Zambia", continent: "Africa", isEU: false, isUN: true },
  ISOCodeZW: { isoCode: "ZW", numericCode: 716, name: "Zimbabwe", continent: "Africa", isEU: false, isUN: false },
  ISOCodeAT: { isoCode: "AT", numericCode: 40, name: "Austria", continent: "Europe", isEU: true, isUN: true },
  ISOCodeBG: { isoCode: "BG", numericCode: 100, name: "Bulgaria", continent: "Europe", isEU: true, isUN: true },
  ISOCodeHR: { isoCode: "HR", numericCode: 191, name: "Croatia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeCY: { isoCode: "CY", numericCode: 196, name: "Cyprus", continent: "Asia", isEU: true, isUN: true },
  ISOCodeCZ: { isoCode: "CZ", numericCode: 203, name: "Czechia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeDK: { isoCode: "DK", numericCode: 208, name: "Denmark", continent: "Europe", isEU: true, isUN: true },
  ISOCodeEE: { isoCode: "EE", numericCode: 233, name: "Estonia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeFI: { isoCode: "FI", numericCode: 246, name: "Finland", continent: "Europe", isEU: true, isUN: true },
  ISOCodeFR: { isoCode: "FR", numericCode: 250, name: "France", continent: "Europe", isEU: true, isUN: true },
  ISOCodeDE: { isoCode: "DE", numericCode: 276, name: "Germany", continent: "Europe", isEU: true, isUN: true },
  ISOCodeGR: { isoCode: "GR", numericCode: 300, name: "Greece", continent: "Europe", isEU: true, isUN: true },
  ISOCodeHU: { isoCode: "HU", numericCode: 348, name: "Hungary", continent: "Europe", isEU: true, isUN: true },
  ISOCodeIE: { isoCode: "IE", numericCode: 372, name: "Ireland", continent: "Europe", isEU: true, isUN: true },
  ISOCodeIT: { isoCode: "IT", numericCode: 380, name: "Italy", continent: "Europe", isEU: true, isUN: true },
  ISOCodeLV: { isoCode: "LV", numericCode: 428, name: "Latvia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeLT: { isoCode: "LT", numericCode: 440, name: "Lithuania", continent: "Europe", isEU: true, isUN: true },
  ISOCodeLU: { isoCode: "LU", numericCode: 442, name: "Luxembourg", continent: "Europe", isEU: true, isUN: true },
  ISOCodeMT: { isoCode: "MT", numericCode: 470, name: "Malta", continent: "Europe", isEU: true, isUN: true },
  ISOCodeNL: { isoCode: "NL", numericCode: 528, name: "Netherlands", continent: "Europe", isEU: true, isUN: true },
  ISOCodePL: { isoCode: "PL", numericCode: 616, name: "Poland", continent: "Europe", isEU: true, isUN: true },
  ISOCodePT: { isoCode: "PT", numericCode: 620, name: "Portugal", continent: "Europe", isEU: true, isUN: true },
  ISOCodeRO: { isoCode: "RO", numericCode: 642, name: "Romania", continent: "Europe", isEU: true, isUN: true },
  ISOCodeSK: { isoCode: "SK", numericCode: 703, name: "Slovakia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeSI: { isoCode: "SI", numericCode: 705, name: "Slovenia", continent: "Europe", isEU: true, isUN: true },
  ISOCodeES: { isoCode: "ES", numericCode: 724, name: "Spain", continent: "Europe", isEU: true, isUN: true },
  ISOCodeSE: { isoCode: "SE", numericCode: 752, name: "Sweden", continent: "Europe", isEU: true, isUN: true },
  ISOCodeXK: { isoCode: "XK", numericCode: 95, name: "Kosovo", continent: "Europe", isEU: true, isUN: true },
}
  